# Site
name: 'New Silkroad Discovery'
#description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
description: ''
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
#disqus: 'demowebsite'
email: 'info@newsilkroaddiscovery.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
mailchimp-list: 'https://gmail.us22.list-manage.com/subscribe/post?u=bcb307094037303e452891e79&id=bf190ba2a8'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    rudy:
      name:           Rudy
      site:           info@newsilkroaddiscovery.com
      avatar:         assets/images/avatar1.png
      bio:            "Hi, I am the Editor of New Silkroad Discovery. I believe interesting stories and insightful knowledge should be free for everyone. I hope you find our news engaging as we explore the dynamic logistics developments along the New Silk Road. Our news is an important source in United Nations reports. 
                      I would love to hear your story. You don’t have to be a C-level executive; I welcome your thoughts on your daily work, doubts, concerns, and questions. We are an open community and welcome your input, with your name or anonymously!"
      email:          info@newsilkroaddiscovery.com
      linkedin: "https://www.linkedin.com/in/newsilkroaddiscovery/"  # Add LinkedIn URL here
      #twitter:        https://twitter.com/wowthemesnet
      


    #jane:
     # name:           Jane
     # site:           http://logistics.newsilkroaddiscovery.com/
     #avatar:         assets/images/avatar2.jpg
     # bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      #email:          info@newsilkroaddiscovery.com
      #linkedin: "https://www.linkedin.com/in/newsilkroaddiscovery/"  # Add LinkedIn URL here
      #twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]